# Generated by Django 2.2.16 on 2020-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201004_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='media',
            field=models.ManyToManyField(default=None, related_name='media', to='app.Product'),
        ),
    ]
