# Generated by Django 2.2.16 on 2020-10-06 05:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201006_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
