# Generated by Django 2.2.16 on 2020-10-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_review_header'),
        ('app', '0008_auto_20201006_1054'),
    ]

    operations = [
    ]
