# Generated by Django 2.2.16 on 2020-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='main_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='products',
            field=models.ManyToManyField(default=None, related_name='products', to='app.Product'),
        ),
    ]
